### ISSUE TITLE
Feature: User can browse the home page and navigate to all pages

### ISSUE THREAD

**Issue by colin-macrae** [colin-macrae/ecommerce-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can browse the home page and navigate to product categories

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can scroll up and down the page to see brand images.  From the navbar, or from links as they scroll down, the user can click on Men's or Women's product categories and navigate to those pages
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/122063836/232239088-eb09273d-3db8-4d75-99db-5afbab1fb8b9.png)
![image](https://user-images.githubusercontent.com/122063836/232239160-25ab7221-b24a-4ba9-b791-cb122f153141.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
- [x] Create HTML and CSS for the home page:
  - [x] Create a navbar and links to "shop men" and "shop women"
  - [x] Create home page images, text, and images with buttons/links to men's and women's apparel
- [x] Create other pages (mens-products.js, womens-products.js, and shopping-cart.js.  
- [x] Create a functional React Router to other pages (those pages can be left blank or have placeholder text for now), and make sure navigation is seamless to all pages 

### 🧑‍⚕️ Clean Up Tasks
- [x] ... 
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
