### ISSUE TITLE
Feature: User can view category pages

### ISSUE THREAD

**Issue by colin-macrae** [colin-macrae/ecommerce-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can navigate to a category of products, e.g. "men's products", and browse all the products under that cateogry.  

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
   

From the home page, the user will see different product categories in the navbar, which they can click to be taken to their category of choice.  Once they reach that page, they will see a list of products loaded.  Each product will have a picture, title, short description, and price listed.    

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/122063836/232252524-87a84e0b-0d2d-40c0-9643-cae996fa5abc.png)
![image](https://user-images.githubusercontent.com/122063836/232252544-068da739-1cb1-463b-8663-4a3adb9f8832.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to include at least 10 jerseys and 10 bibs (men's category)

### ☁️ Server Tasks

- [x] Test server with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update the homepage component to be able to display items, two side by side in mobile, and four side by side on desktop
  - [x] set up express app and corresponding request responses
  - [x] set up fetch request and test it to confirm (in console if needed) that it's functioning 
  - [x] render fetched data on the webpage using the map() function and simply putting it in a UL for now
  - [x] create a component to render one whole item which includes all data (type, gender, pic, price etc.)
    - [x] create the actual component and put dummy data in it so that you can see its structure 
    - [x] once the previous step is done, look at its structure and decide how you are going to populate that component with data from the database.  Attempt to create that component and have it render correctly.  The component needs to be able to be duplicated and automatically replicate based on the number of items in the database. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
