### ISSUE TITLE
Feature: User can click on and see item details

### ISSUE THREAD

**Issue by colin-macrae** [colin-macrae/ecommerce-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/122063836/232252588-a1757eb2-9250-4948-a8b0-95fc0eb51dfe.png)
![image](https://user-images.githubusercontent.com/122063836/232252603-caafffbc-1e84-40fb-b1fa-365e87badb06.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to respond to get requests with productId as the endpoint
- [x] On the product pages, each the men's page and women's page, wrap the component in a link whose endpoint goes to `/productdetails/${productId}`
- [x] Create a page called "ProductDetails", along with a matching CSS file
- [x] In the .js file, create a fetch request to the backend which grabs the product's details 
- [x] Make sure all the paths line up: 
  - [x] From the page's fetch to the express app, the endpoints 
- [x] Create the CSS so the page renders as designed, in mobile and desktop

### 🧑‍⚕️ Clean Up Tasks

- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
