### ISSUE TITLE
Feature: User can add items to a shopping cart 

### ISSUE THREAD

**Issue by colin-macrae** [colin-macrae/ecommerce-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add items to cart by clicking "add to cart" 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

While on the product details page of a given product, the user can click the "ADD TO CART" button, which will add that item to their shopping cart.  When they click on the cart icon at the top of the page, they will be taken to their cart where they can view all the items they have thus far added to cart. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/122063836/232252653-76598861-7c0b-4f29-9374-5cd59aea3b10.png)
![image](https://user-images.githubusercontent.com/122063836/232252678-96d02aff-ec80-470e-b4a1-9c021e246876.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
- [x] Create a page for shopping cart, with a corresponding css file
- [x] Create a component for displaying items which are added to the cart 
- [x] Create functionality so that when a button is clicked: 
  - [x] That product and the needed info is grabbed 
  - [x] That info is sent to local storage in json format 
  - [x] That info is sent to something like a "data" variable from which the browser can get the data 
  - [x] Make it so on unload, it stores, then on load, it re-grabs and loads the page (look at AJAX as an example) 

### 🧑‍⚕️ Clean Up Tasks

- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
