### ISSUE TITLE
Feature: User can delete items from shopping cart

### ISSUE THREAD

**Issue by colin-macrae** [colin-macrae/ecommerce-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/122063836/232252740-47eee6d2-45b8-4945-971d-aaf1cde33566.png)

![image](https://user-images.githubusercontent.com/122063836/232252719-b7377ce2-3e7a-4ad9-b87a-ada81a8f8c5d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
